# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/lab6_block/lab6_block.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab6_block || ORIG_REF_NAME==lab6_block} -quiet] -quiet

# IP: bd/lab6_block/ip/lab6_block_processing_system7_0_0/lab6_block_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab6_block_processing_system7_0_0 || ORIG_REF_NAME==lab6_block_processing_system7_0_0} -quiet] -quiet

# IP: bd/lab6_block/ip/lab6_block_ps7_0_axi_periph_0/lab6_block_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab6_block_ps7_0_axi_periph_0 || ORIG_REF_NAME==lab6_block_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/lab6_block/ip/lab6_block_rst_ps7_0_100M_0/lab6_block_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab6_block_rst_ps7_0_100M_0 || ORIG_REF_NAME==lab6_block_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/lab6_block/ip/lab6_block_xbar_0/lab6_block_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab6_block_xbar_0 || ORIG_REF_NAME==lab6_block_xbar_0} -quiet] -quiet

# IP: bd/lab6_block/ip/lab6_block_PmodOLED_0_0/lab6_block_PmodOLED_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab6_block_PmodOLED_0_0 || ORIG_REF_NAME==lab6_block_PmodOLED_0_0} -quiet] -quiet

# IP: bd/lab6_block/ip/lab6_block_PmodRTCC_0_0/lab6_block_PmodRTCC_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab6_block_PmodRTCC_0_0 || ORIG_REF_NAME==lab6_block_PmodRTCC_0_0} -quiet] -quiet

# IP: bd/lab6_block/ip/lab6_block_auto_pc_0/lab6_block_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab6_block_auto_pc_0 || ORIG_REF_NAME==lab6_block_auto_pc_0} -quiet] -quiet

# XDC: bd/lab6_block/lab6_block_ooc.xdc
